services:
  frontend:
    build: frontend/
    # image: todo-frontend
    ports:
      - "3000:3000"

  backend:
    build: backend/
    # image: todo-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
     - mongo:db


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"